# Generated by Django 4.2 on 2023-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Xaridor', 'verbose_name_plural': 'Xaridorlar'},
        ),
    ]
