# Generated by Django 4.2 on 2023-05-02 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_options_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='full_name',
            field=models.CharField(max_length=255, null=True, verbose_name="To'liq nomi"),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True, verbose_name='Narxi'),
        ),
    ]
