# Generated by Django 4.2 on 2023-05-16 04:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_charactory_country_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='unit_name',
            field=models.UUIDField(default=uuid.UUID('21a83ac2-68a7-4699-91ee-497c77a7ecc1'), unique=True, verbose_name='Takrorlanmas_id'),
        ),
    ]
