# Generated by Django 4.2 on 2023-05-16 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productprice_unit_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Mahsulot xususiyati',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoriya', 'verbose_name_plural': 'Categoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Davlat', 'verbose_name_plural': 'Davlatlar'},
        ),
        migrations.AlterModelOptions(
            name='manufactory',
            options={'verbose_name': 'Ishlab Chiqqan Zavod', 'verbose_name_plural': 'Ishlab Chiqqan Zavodlar'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Mahsulot', 'verbose_name_plural': 'Mahsulotlar'},
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Ota kategoriya'),
        ),
        migrations.AddField(
            model_name='productprice',
            name='unit_type',
            field=models.CharField(default='', max_length=255, verbose_name="O'lchov birligi"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='product.category', verbose_name='Kategoriya'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.country', verbose_name='Ishlab chiqligan davlat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Holati Aktiv'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_count',
            field=models.IntegerField(default=0, verbose_name='Sotilganlar soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0, verbose_name="Ko'rganlar soni"),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_media', to='product.product', verbose_name='Mahsulot'),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_price', to='product.product', verbose_name='Mahsulot'),
        ),
        migrations.RenameModel(
            old_name='Charactory',
            new_name='Character',
        ),
        migrations.DeleteModel(
            name='ProductCharactory',
        ),
        migrations.AddField(
            model_name='productcharacter',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.character', verbose_name='Mahsulot xususiyati'),
        ),
        migrations.AddField(
            model_name='productcharacter',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_character', to='product.product', verbose_name='Mahsulot'),
        ),
    ]
