# Generated by Django 4.2 on 2023-05-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productcharacter_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='manufactory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='manufactory_re', to='product.manufactory', verbose_name='Ishlab chiqqan Korxona'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media',
            field=models.FileField(null=True, upload_to='product/media', verbose_name='Video/Rasm'),
        ),
    ]
