# Generated by Django 4.2 on 2023-05-23 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/product/category_images', verbose_name='Categoriya rasimi'),
        ),
    ]
