# Generated by Django 4.2 on 2023-05-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product/category_images', verbose_name='Categoriya rasimi'),
        ),
    ]
