# Generated by Django 4.2 on 2023-05-23 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media',
            field=models.FileField(null=True, upload_to='product/product_images', verbose_name='Video/Rasm'),
        ),
    ]
