# Generated by Django 4.2 on 2023-06-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sale_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Sotilganlar soni'),
        ),
        migrations.AlterField(
            model_name='product',
            name='view_count',
            field=models.PositiveBigIntegerField(blank=True, default=0, null=True, verbose_name="Ko'rganlar soni"),
        ),
    ]
