# Generated by Django 4.2 on 2023-06-06 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_product_sale_count_alter_product_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='media',
            field=models.FileField(default=None, upload_to='product/product_images', verbose_name='Video/Rasm'),
            preserve_default=False,
        ),
    ]
