# Generated by Django 4.2 on 2023-04-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlay',
            name='outlay_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.outlaycategory', verbose_name='Xarajot kategoriyasi'),
        ),
    ]
