# Generated by Django 4.2 on 2023-04-09 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Baza', 'verbose_name_plural': 'Bazalar'},
        ),
        migrations.AlterModelOptions(
            name='warehouseproduct',
            options={'verbose_name': 'Bazadagi maxsulot', 'verbose_name_plural': 'Bazadagi maxsulotlar'},
        ),
    ]
