# Generated by Django 4.2 on 2023-04-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseproduct',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=17, null=True, verbose_name='Summasi'),
        ),
    ]
