# Generated by Django 4.2 on 2023-04-17 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_warehouseproduct_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_warehouse', to='warehouse.warehouse', verbose_name='Bazadan')),
                ('to_warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_warehouse', to='warehouse.warehouse', verbose_name='Bazaga')),
            ],
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='income',
        ),
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(verbose_name='Maxsulot soni')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.movement', verbose_name="Ko'chirma")),
                ('warehouse_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct', verbose_name='Maxsulot')),
            ],
        ),
    ]
