# Generated by Django 4.2 on 2023-04-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_movement_remove_warehouseproduct_income_movementitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='status',
            field=models.CharField(choices=[('created', 'Yaratilgan'), ('accepted', 'Tasdiqlangan'), ('completed', 'Tugallangan'), ('canceled', 'Rad etilgan')], max_length=255, null=True, verbose_name='Statusi'),
        ),
    ]
