# Generated by Django 4.2 on 2023-05-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_remove_order_warehouse'),
        ('income', '0005_remove_income_warehouse'),
        ('warehouse', '0008_remove_warehouseproduct_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movementitem',
            name='movement',
        ),
        migrations.RemoveField(
            model_name='movementitem',
            name='warehouse_product',
        ),
        migrations.RemoveField(
            model_name='warehouseproduct',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Movement',
        ),
        migrations.DeleteModel(
            name='MovementItem',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
