# Generated by Django 4.2 on 2023-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Yitkazib beruvchi')),
                ('phone', models.CharField(max_length=13)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Balansi')),
            ],
        ),
    ]
