# Generated by Django 4.2 on 2023-04-05 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yasalgan vaqti')),
                ('status', models.CharField(choices=[('created', 'Yaratilgan'), ('accepted', 'Tasdiqlangan'), ('completed', 'Tugallangan'), ('canceled', 'Rad etilgan')], max_length=255, verbose_name='Statusi')),
                ('total', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Narxi')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='provider.provider', verbose_name='Yitkazib beruvchi')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Narxi')),
                ('count', models.IntegerField(verbose_name='Soni')),
                ('total', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Summasi')),
                ('income', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='income.income', verbose_name='Krim')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product', verbose_name='Maxsulot')),
            ],
        ),
    ]
