# Generated by Django 4.2 on 2023-04-11 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_warehouseproduct_total'),
        ('income', '0002_alter_income_options_alter_incomeitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Baza'),
        ),
    ]
