# Generated by Django 4.2 on 2023-05-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0003_income_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='status',
            field=models.CharField(choices=[('created', 'Yaratilgan'), ('accepted', 'Tasdiqlangan'), ('completed', 'Tugallangan'), ('canceled', 'Rad etilgan')], default='created', max_length=255, verbose_name='Statusi'),
        ),
        migrations.AlterField(
            model_name='income',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, verbose_name='Narxi'),
        ),
    ]
