# Generated by Django 4.2 on 2023-05-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_alter_income_status_alter_income_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='warehouse',
        ),
    ]
