# Generated by Django 4.2 on 2023-04-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('director', 'Director'), ('admin', 'Admin'), ('seller', 'Soruvchi')], default='seller', max_length=255, verbose_name='Foydalanuvchi turi'),
        ),
    ]
