# Generated by Django 4.2 on 2023-04-06 18:06

from django.db import migrations, models
import django_resized.forms
import user.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[400, 400], upload_to='user_avatars/', verbose_name='Rasim'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=255, null=True, validators=[user.validators.phone_validator], verbose_name='Telefon raqami'),
        ),
    ]
