# Generated by Django 4.2 on 2023-04-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_warehouseproduct_income'),
        ('order', '0003_orderitem_varehouseproduct_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='varehouseproduct',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouse_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouseproduct'),
        ),
    ]
