# Generated by Django 4.2 on 2023-04-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_orderitem_varehouseproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='warehouse_product',
        ),
    ]
