# Generated by Django 4.2 on 2023-04-25 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_movement_status'),
        ('order', '0005_remove_orderitem_warehouse_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse', verbose_name='Baza'),
        ),
    ]
