# Generated by Django 4.2 on 2023-04-25 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0006_movement_status'),
        ('order', '0006_order_warehouse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='warehouseproduct',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouseproduct', verbose_name='Maxsulot'),
            preserve_default=False,
        ),
    ]
