# Generated by Django 4.2 on 2023-04-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_remove_orderitem_product_orderitem_warehouseproduct'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='warehouseproduct',
            new_name='warehouse_product',
        ),
    ]
