# Generated by Django 4.2 on 2023-05-27 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_rename_warehouseproduct_orderitem_warehouse_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='warehouse',
        ),
    ]
